[package]
name = "oboron-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "_oboron"
crate-type = ["cdylib"]

[features]
default = ["all-schemes", "legacy", "experimental", "keyless", "legacy", "ob70"]

ob00 = ["oboron/ob00"]
ob01 = ["oboron/ob01"]
ob31 = ["oboron/ob31"]
ob32 = ["oboron/ob32"]
ob21p = ["oboron/ob21p"]
ob31p = ["oboron/ob31p"]
ob32p = ["oboron/ob32p"]
ob70 = ["oboron/ob70"]
ob71 = ["oboron/ob71"]
all-schemes = ["ob01", "ob21p", "ob31", "ob31p", "ob32", "ob32p"]

keyless = ["oboron/keyless"]

# Feature groups
legacy = ["ob00"]  # For compatibility/testing
experimental = []  # Experimental algorithms

[dependencies]
oboron = { version = "0.2", path = "../oboron", default-features = false, features=["full"] }
pyo3 = { version = "0.22", features = ["extension-module"] }
hex = "0.4"

